# Generated by Django 4.0.2 on 2022-02-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyphoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post_num',
        ),
    ]
