# Generated by Django 4.0.1 on 2022-02-11 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyphoto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaliconset',
            old_name='icon_set_weather_is_setted',
            new_name='emotion_is_setted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='icon_set_weather',
        ),
        migrations.AddField(
            model_name='personaliconset',
            name='weather_is_setted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='icon_emotion',
            field=models.CharField(default='happy', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='icon_weather',
            field=models.CharField(default='sunny', max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyphoto.answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyphoto.post')),
            ],
        ),
    ]
