# Generated by Django 4.0.2 on 2022-02-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyphoto', '0003_profile_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
