# Generated by Django 4.0.2 on 2022-02-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyphoto', '0004_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
