

# Generated by Django 4.0.2 on 2022-02-22 07:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyphoto', '0005_alter_profile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaliconset',
            name='author',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='PersonalIconSet',
        ),
    ]
